[tool.poetry]
name = "chapter-1"
version = "0.1.0"
description = ""
authors = ["hak@thinkstation <zlp@upc.edu.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
